server:
  port: 9090
  application:
    name: ApiGateway

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: ORDER-SERVICE
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/order/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: order-service-cb
#                fallbackUri: forward:/fallback/orderServiceFallback
        - id: PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/product/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: product-service-cb
#                fallbackUri: forward:/fallback/productServiceFallback
        - id: PAYMENT-SERVICE
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/v1/payment/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: payment-service-cb
#                fallbackUri: forward:/fallback/paymentServiceFallback
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}

management:
  tracing:
    sampling:
      probability: 1.0